### ISSUE TITLE
测试数据output.txt

### ISSUE THREAD

**Issue by hejiao610** [MarcWong/SemanticMVS#2]
@MarcWong 非常感谢这个开源项目，请问测试数据  二三维匹配文件output.txt是如何产生的？谢谢

**Comment by MarcWong** [comment]
这个文件是记录了openMVS的匹配信息，目前的实现比较粗暴，直接把openMVS的稠密点云与他对应的图片id、像素坐标都记录下来了。这个文件的格式大概是这样：
```
X Y Z (三维点坐标)
n (对应的图片数量)
ID1 U1 V1 (第i张图片id、像素坐标)
ID2 U2 V2
...
IDn Un Vn
```

至于稠密点云和二维图片的对应信息如何获取，可以参见openMVS的官方库： https://github.com/cdcseacave/openMVS/blob/master/libs/MVS/SceneDensify.cpp
